<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>D:\ITSHOP-267_2409\MicroserviceBase\bin\Debug\netcoreapp2.2\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eid.Microservices.Core\Eid.Microservices.Core.csproj" />
  </ItemGroup>

</Project>
