using Eid.Microservices.MongoDb.Helpers;
using System;
using System.Linq;
using System.Reflection;

namespace Eid.Microservices.MongoDb.Models
{
    /// <summary>
    /// Helper class used for wrapping necessary elements that describe the Key/Id property of an entity used in IRepository<T>
    /// </summary>
    /// <typeparam name="T">Entity type.</typeparam>
    public sealed class EntityKey<T> where T : class
    {
        public string PropertyName { get; }
        public Type PropertyType { get; }
        public PropertyInfo PropertyInfo { get; }

        public bool IsAutoGenerated { get; }

        private EntityKey(PropertyInfo propertyInfo, bool autoGenerated = false)
        {
            PropertyInfo = propertyInfo ?? throw new ArgumentNullException(nameof(propertyInfo));
            IsAutoGenerated = autoGenerated;

            PropertyName = PropertyInfo.Name;
            PropertyType = PropertyInfo.PropertyType;
        }

        /// <summary>
        /// Gets the value of the Key/Id property for a givent entity.
        /// </summary>
        /// <param name="entity">Entity being evaluated.</param>
        /// <returns>Value of the entity property.</returns>
        public object GetEntityKeyValue(T entity)
        {
            if (entity == null)
                throw new ArgumentNullException(nameof(entity));

            return PropertyInfo.GetValue(entity);
        }

        /// <summary>
        /// Examine if the Key/Id property value is equal to the default value of that type.
        /// </summary>
        /// <param name="entity">Entity being evaluated.</param>
        /// <returns>Boolean if it is equal.</returns>
        public bool IsKeyValueNullOrDefault(T entity)
        {
            var defaultKeyValue = PropertyType.GetDefaultValue();
            return GetEntityKeyValue(entity).Equals(defaultKeyValue);
        }

        /// <summary>
        /// Given an entity used in IRepository, this method will try and discover which property is used as a Key/Id property.
        /// </summary>
        /// <returns>Insatnce of a new EntityKey for  given entity T.</returns>
        public static EntityKey<T> Discover()
        {
            var properties = typeof(T).GetRuntimeProperties();
            EntityKey<T> result = null;

            // iterate trough properties until one has the custom attribute
            foreach (var prop in properties)
            {
                var entityKeyAttribute = prop.GetCustomAttribute<EntityKeyAttribute>(true);
                if (entityKeyAttribute != null)
                {
                    result = new EntityKey<T>(prop, entityKeyAttribute.AutoGenerated);
                    break;
                }
            }

            // if no attribute found, try and find an Id property
            if (result == null)
            {
                var idProperty = properties.SingleOrDefault(prop => prop.Name.ToLowerInvariant() == "id");

                if (idProperty != null)
                    result = new EntityKey<T>(idProperty);
            }

            return result;
        }
    }
}
