using Eid.Microservices.MongoDb.Interface;
using Eid.Microservices.MongoDb.Models;
using Eid.Microservices.MongoDb.Helpers;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization.Formatters.Binary;


namespace EmpowerID.Common
{
    public class InMemoryRepository<T> : IRepository<T> where T : class
    {
        private static ConcurrentDictionary<object, T> _storage;
        private static readonly EntityKey<T> _entityKey;

        #region [CTOR]

        static InMemoryRepository()
        {
            _storage = new ConcurrentDictionary<object, T>();
            _entityKey = EntityKey<T>.Discover() ??
                throw new ApplicationException($"InMemoryRepository - Can not identify Id/Key property for Type[{typeof(T).Name}]");
        }

        #endregion

        #region [Public]

        public bool Insert(T entity)
        {
            var result = false;
            object lastKey = _entityKey.GetEntityKeyValue(entity);

            if (entity != null)
            {
                // if auto-generate true, set new value for the key property
                if (_entityKey.IsAutoGenerated)
                {
                    var newId = GenerateNewKey();
                    _entityKey.PropertyInfo.SetValue(entity, newId);
                }

                if (!_entityKey.IsKeyValueNullOrDefault(entity))
                {
                    var cloned = QuickReplicate(entity);
                    var id = _entityKey.GetEntityKeyValue(cloned);

                    if (_storage.TryAdd(id, cloned))
                        result = true;
                    else
                        _entityKey.PropertyInfo.SetValue(entity, lastKey);
                }
                else
                    throw new InvalidOperationException($"Trying to insert entity where the key property [{_entityKey.PropertyName}] has null or default value.");
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public bool Upsert(T entity)
        {
            var result = false;

            if (entity != null)
            {
                // if entity has an auto-generated key
                // if id has default value (null or default(valueType)) it translated to insert operation
                // if id is not default value (null or default(valueType)), try to find entity and update it (but no upsert)
                if (_entityKey.IsAutoGenerated)
                {
                    if (_entityKey.IsKeyValueNullOrDefault(entity))
                        result = Insert(entity);
                    else
                        result = Update(entity);
                }
                else
                {
                    // if entity has a normal id/key property, do normal upsert flow
                    result = true;

                    if (!Update(entity))
                        result = Insert(entity);
                }
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public bool Delete(T entity)
        {
            var result = false;

            if (entity != null)
            {
                var key = _entityKey.GetEntityKeyValue(entity);

                if (key != null)
                    result = Delete(key);
            }
            else
            {
                throw new ArgumentNullException(nameof(entity));
            }

            return result;
        }

        public bool Delete(object id)
        {
            var result = false;

            if (id != null)
            {
                result = _storage.TryRemove(id, out _);
            }
            else
            {
                throw new ArgumentNullException(nameof(id));
            }

            return result;
        }

        public IEnumerable<T> GetAll(Expression<Func<T, bool>> where = null)
        {
            return where == null ? _storage.Values.ToList() :
                                   _storage.Values.Where(where.Compile()).ToList();
        }

        public PaginatedResult<T> GetAllPaginated(int pageIndex, int pageSize, Expression<Func<T, bool>> where = null)
        {
            if (pageIndex < 0 || pageSize < 1)
                throw new ArgumentOutOfRangeException($"Arguments {nameof(pageIndex)} or {nameof(pageSize)} are out of range.");

            var data = where == null ?
                       _storage.Values :
                       _storage.Values.Where(where.Compile());

            var dataPaginated = data.Skip(pageIndex)
                                    .Take(pageSize)
                                    .ToList();

            return new PaginatedResult<T>(dataPaginated, data.Count(), pageIndex, pageSize);
        }

        public T Get(object id)
        {
            T result;

            if (id != null)
            {
                _storage.TryGetValue(id, out result);
            }
            else
            {
                throw new ArgumentNullException(nameof(id));
            }

            return result;
        }

        public bool Update(T entity, params string[] propertiesToUpdate)
        {
            var result = false;

            if (entity != null)
            {
                var key = _entityKey.GetEntityKeyValue(entity);

                if (key != null && _storage.ContainsKey(key))
                {
                    if (_storage.TryRemove(key, out T currentEntity))
                    {
                        T cloned;

                        // if param list empty, assume we want to update every property (replace operation)
                        if (propertiesToUpdate.Length == 0)
                        {
                            cloned = QuickReplicate(entity);
                        }
                        else
                        {
                            cloned = QuickReplicate(currentEntity);

                            foreach (var prop in propertiesToUpdate)
                            {
                                // skip if primary key prop in the list
                                if (prop != _entityKey.PropertyName)
                                {
                                    var propInfo = typeof(T).GetRuntimeProperty(prop);

                                    if (propInfo != null)
                                    {
                                        var newValue = propInfo.GetValue(entity);
                                        propInfo.SetValue(cloned, newValue);
                                    }
                                }
                            }
                        }

                        result = _storage.TryAdd(key, cloned);
                    }
                }
            }
            else
            {
                throw new ArgumentNullException(nameof(entity));
            }

            return result;
        }

        public long TotalCount()
        {
            return _storage.Count;
        }

        #endregion

        #region [Helper, Non-Interface Methods]

        public void ClearAll()
        {
            _storage.Clear();
        }

        public bool Seed(IEnumerable<T> data)
        {
            var result = false;

            // only allow seeding if new/clean repo is being used
            if (data != null && data.Any())
            {
                if (_storage.IsEmpty)
                {
                    Dictionary<object, T> dict = new Dictionary<object, T>();
                    var defaultKeyValue = _entityKey.PropertyType.GetDefaultValue();

                    foreach (var obj in data)
                    {
                        var key = _entityKey.GetEntityKeyValue(obj);

                        if (_entityKey.IsAutoGenerated)
                        {
                            dict.Add(dict.ContainsKey(key) ? GenerateNewKey() : key, obj);
                        }
                        else
                        {
                            // if not autogenerated key, check for duplicate/null/default(...) key values
                            if (!key.Equals(defaultKeyValue) && !dict.ContainsKey(key))
                                dict.Add(key, obj);
                        }
                    }

                    _storage = new ConcurrentDictionary<object, T>(dict.AsEnumerable());
                    result = true;
                }
            }

            return result;
        }

        #endregion

        #region [Private]

        private object GenerateNewKey()
        {
            object result = null;

            if (_entityKey.PropertyType == typeof(string) || _entityKey.PropertyType == typeof(Guid))
            {
                while (true)
                {
                    result = _entityKey.PropertyType == typeof(Guid) ?
                             Guid.NewGuid() :
                             (object)Guid.NewGuid().ToString();

                    if (!_storage.ContainsKey(result))
                        break;
                }
            }
            else if (_entityKey.PropertyType == typeof(int))
            {
                if (_storage.Count > 0)
                {
                    var lastEntity = _storage.LastOrDefault();
                    result = lastEntity.Key;

                    while (true)
                    {
                        result = ((int)result) + 1;

                        if (!_storage.ContainsKey(result))
                            break;
                    }
                }
                else
                    result = 1;
            }

            if (result == null)
                throw new Exception($"Unsupported primary key type [{_entityKey.PropertyType.Name}]");

            return result;
        }

        private T QuickReplicate(T entity)
        {
            T result = null;

            if (entity != null)
            {
                using (var stream = new MemoryStream())
                {
                    var formatter = new BinaryFormatter();
                    formatter.Serialize(stream, entity);
                    stream.Seek(0, SeekOrigin.Begin);
                    var copy = formatter.Deserialize(stream) as T;

                    result = copy;
                }
            }

            return result;
        }

        #endregion
    }
}
