using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Bson.Serialization;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Eid.Microservices.MongoDb.Helpers;
using Eid.Microservices.MongoDb.Interface;
using Eid.Microservices.MongoDb.Models;

namespace EmpowerID.Common
{
    public class MongoDBRepository<T> : IRepository<T> where T : class
    {
        private readonly IMongoClient _mongoClient;
        private readonly IMongoDatabase _db;
        private readonly IMongoCollection<T> _collection;
        private readonly ILogger<MongoDBRepository<T>> _loggeer;

        private static readonly string _entityName;
        private static readonly EntityKey<T> _entityKey;

        #region [CTOR]

        public MongoDBRepository(IMongoDatabase mongoDatabase, ILogger<MongoDBRepository<T>> logger)
        {
            _db = mongoDatabase;
            _mongoClient = mongoDatabase.Client;
            _collection = _db.GetCollection<T>(_entityName);

            _loggeer = logger;
        }

        static MongoDBRepository()
        {
            _entityName = typeof(T).Name;
            _entityKey = EntityKey<T>.Discover() ??
                throw new ApplicationException($"MongoDBRepository - Can not identify Id/Key property for Type[{typeof(T).Name}]");

            ConfigureBasicMappings();
        }

        #endregion

        public bool Insert(T entity)
        {
            var result = false;
            var id = _entityKey.GetEntityKeyValue(entity);

            if (entity != null)
            {
                // if auto-generate true, set new value for the key property
                if (_entityKey.IsAutoGenerated)
                {
                    var newId = GenerateNewKey();
                    _entityKey.PropertyInfo.SetValue(entity, newId);
                }

                try
                {
                    if (!_entityKey.IsKeyValueNullOrDefault(entity))
                    {
                        _collection.InsertOne(entity);
                        result = true;
                    }
                    else
                        throw new InvalidOperationException($"Trying to insert entity where the key property [{_entityKey.PropertyName}] has null or default value.");
                }
                catch (MongoException e)
                {
                    _loggeer.LogError(e, $"Exception thrown while performing a Insert<{_entityName}> operation. Entity Id [{id}], AutoGenerateId[{_entityKey.IsAutoGenerated}].");

                    // if autoGenerated id, set back the old id before trying to insert
                    if (_entityKey.IsAutoGenerated)
                        _entityKey.PropertyInfo.SetValue(entity, id);
                }
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public bool Upsert(T entity)
        {
            var result = false;

            if (entity != null)
            {
                // if entity has an auto-generated key
                // if id has default value (null or default(valueType)) it translated to insert operation
                // if id is not default value, try to find entity and replace it (but no upsert)
                if (_entityKey.IsAutoGenerated)
                {
                    if (_entityKey.IsKeyValueNullOrDefault(entity))
                        result = Insert(entity);
                    else
                        result = Update(entity);
                }
                else
                {
                    // if entity has a normal id property, do normal upsert
                    var id = _entityKey.GetEntityKeyValue(entity);

                    try
                    {
                        var replaceResult = _collection.ReplaceOne(Builders<T>.Filter.Eq("_id", id), entity, new UpdateOptions() { IsUpsert = true });
                        result = replaceResult.IsAcknowledged && (replaceResult.ModifiedCount > 0 || replaceResult.UpsertedId?.IsBsonNull == false);
                    }
                    catch (MongoException e)
                    {
                        _loggeer.LogError(e, $"Exception thrown while performing a Upsert<{_entityName}> operation. Entity Id [{id}].");
                    }
                }
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public bool Delete(object id)
        {
            var result = false;

            if (id != null)
            {
                try
                {
                    var deleteResult = _collection.DeleteOne(Builders<T>.Filter.Eq("_id", id));
                    result = deleteResult.IsAcknowledged && deleteResult.DeletedCount > 0;
                }
                catch (MongoException e)
                {
                    _loggeer.LogError(e, $"Exception thrown while performing a Delete<{_entityName}> operation. Entity Id [{id}].");
                }
            }
            else
                throw new ArgumentNullException(nameof(id));

            return result;
        }

        public bool Delete(T entity)
        {
            var result = false;

            if (entity != null)
            {
                var entityKeyValue = _entityKey.GetEntityKeyValue(entity);
                result = Delete(entityKeyValue);
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public T Get(object id)
        {
            if (id == null)
                throw new ArgumentNullException(nameof(id));

            return _collection.FindSync(Builders<T>.Filter.Eq("_id", id))
                              .SingleOrDefault();
        }

        public IEnumerable<T> GetAll(Expression<Func<T, bool>> where = null)
        {
            var result = new List<T>();

            try
            {
                var list = _collection.FindSync(where ?? FilterDefinition<T>.Empty);
                result.AddRange(list.ToEnumerable());
            }
            catch (Exception e)
            {
                _loggeer.LogError(e, $"Exception thrown while performing a GetAll<{_entityName}> operation. Where filter [{where?.ToString()}]");
            }

            return result;
        }

        public PaginatedResult<T> GetAllPaginated(int pageIndex, int pageSize, Expression<Func<T, bool>> where = null)
        {
            if (pageIndex < 0 || pageSize < 1)
                throw new ArgumentOutOfRangeException($"Arguments {nameof(pageIndex)} or {nameof(pageSize)} are out of range.");

            var result = new PaginatedResult<T>(null, 0, pageIndex, pageSize);

            try
            {
                var query = _collection.Find(where ?? FilterDefinition<T>.Empty);

                var total = query.Count();
                var pagedQuery = query.Skip(pageIndex).Limit(pageSize);

                result = new PaginatedResult<T>(pagedQuery.ToEnumerable(), total, pageIndex, pageSize);
            }
            catch (Exception e)
            {
                _loggeer.LogError(e, $"Exception thrown while performing a GetAllPaginated<{_entityName}> operation. Where filter [{where?.ToString()}]");
            }

            return result;
        }

        public bool Update(T entity, params string[] propertiesToUpdate)
        {
            var result = false;

            if (entity != null)
            {
                var id = _entityKey.GetEntityKeyValue(entity);

                try
                {
                    if (propertiesToUpdate.Length == 0)
                    {
                        // Replace operation
                        var replaceResult = _collection.ReplaceOne(Builders<T>.Filter.Eq("_id", id), entity, new UpdateOptions() { IsUpsert = false });
                        result = replaceResult.IsAcknowledged && replaceResult.ModifiedCount > 0;
                    }
                    else
                    {
                        // Update specific fields - operation
                        List<UpdateDefinition<T>> updateDefininitions = new List<UpdateDefinition<T>>();
                        var propertyValues = GetPropertyValues(entity);

                        for (int i = 0; i < propertiesToUpdate.Length; i++)
                        {
                            var propertyName = propertiesToUpdate[i];

                            // first make sure, property we are trying to update is not the Id/Key property
                            // second, make sure property (and value) exist in the given entity
                            if (propertyName != _entityKey.PropertyName && propertyValues.ContainsKey(propertyName))
                                updateDefininitions.Add(Builders<T>.Update.Set(propertyName, propertyValues[propertyName]));
                        }

                        // if anything to update after evaluation
                        if (updateDefininitions.Any())
                        {
                            var combinedUpdates = Builders<T>.Update.Combine(updateDefininitions);

                            var replaceResult = _collection.UpdateOne(Builders<T>.Filter.Eq("_id", id), combinedUpdates, new UpdateOptions() { IsUpsert = false });
                            result = replaceResult.IsAcknowledged && replaceResult.ModifiedCount > 0;
                        }
                    }
                }
                catch (MongoException e)
                {
                    _loggeer.LogError(e, $"Exception thrown while performing a Update<{_entityName}> operation. Entity Id [{id}].");
                }
            }
            else
                throw new ArgumentNullException(nameof(entity));

            return result;
        }

        public long TotalCount()
        {
            return _collection.Count(FilterDefinition<T>.Empty);
        }

        #region [Helper, Non-Interface Methods]

        public void ClearAll()
        {
            _db.DropCollection(_entityName);
        }

        public bool Seed(IEnumerable<T> entities)
        {
            var result = false;

            if (entities != null && entities.Any())
            {
                // only allow seeding if collection is new/empty
                if (TotalCount() == 0)
                {
                    var nonDuplicateDict = new Dictionary<object, T>();
                    var defaultKeyValue = _entityKey.PropertyType.GetDefaultValue();

                    foreach (var entity in entities)
                    {
                        var key = _entityKey.GetEntityKeyValue(entity);

                        if (_entityKey.IsAutoGenerated)
                        {
                            nonDuplicateDict.Add(nonDuplicateDict.ContainsKey(key) ? GenerateNewKey() : key, entity);
                        }
                        else
                        {
                            // if not autogenerated key, check for duplicate/null/default(...) key values
                            if (!key.Equals(defaultKeyValue) && !nonDuplicateDict.ContainsKey(key))
                                nonDuplicateDict.Add(key, entity);
                        }
                    }

                    try
                    {
                        _collection.InsertMany(nonDuplicateDict.Values);
                        result = true;
                    }
                    catch (Exception e)
                    {
                        _loggeer.LogError(e, $"Exception thrown while trying to seed data for {nameof(MongoDBRepository<T>)} of type [{typeof(T).Name}]");
                    }
                }
            }

            return result;
        }

        public static void OverrideMappings(Action<BsonClassMap<T>> init)
        {
            BsonClassMap.RegisterClassMap<T>(init);
        }

        #endregion

        #region [Private]

        private IDictionary<string, object> GetPropertyValues(T entity)
        {
            var result = new Dictionary<string, object>();

            if (entity != null)
            {
                var properties = typeof(T).GetRuntimeProperties();

                foreach (var property in properties)
                    result.Add(property.Name, property.GetValue(entity));
            }

            return result;
        }

        private object GenerateNewKey()
        {
            object result = null;

            if (_entityKey.PropertyType == typeof(string) || _entityKey.PropertyType == typeof(Guid))
            {
                while (true)
                {
                    result = _entityKey.PropertyType == typeof(Guid) ?
                             Guid.NewGuid() :
                             (object)Guid.NewGuid().ToString();

                    // check if already existing
                    if (Get(result) == null)
                        break;
                }
            }
            else if (_entityKey.PropertyType == typeof(ObjectId))
            {
                while (true)
                {
                    result = ObjectId.GenerateNewId();

                    // check if already existing
                    if (Get(result) == null)
                        break;
                }
            }

            if (result == null)
                throw new Exception($"Unsupported primary key type [{_entityKey.PropertyType.Name}]");

            return result;
        }

        private static void ConfigureBasicMappings()
        {
            if (BsonClassMap.IsClassMapRegistered(typeof(T)))
                return;

            BsonClassMap.RegisterClassMap<T>(cm =>
            {
                cm.AutoMap();
                cm.SetIgnoreExtraElements(true);

                if(_entityKey.PropertyName.ToLowerInvariant() != "id")
                    cm.MapIdMember(_entityKey.PropertyInfo);
            });
        }

        #endregion
    }
}
