using System;

namespace Eid.Microservices.MongoDb.Helpers
{
    [AttributeUsage(AttributeTargets.Property)]
    public class EntityKeyAttribute : Attribute
    {
        public EntityKeyAttribute()
        {
            AutoGenerated = false;
        }

        /// <summary>
        /// If the value of the Primary Key property should be auto generated. Default: false
        /// </summary>
        public bool AutoGenerated { get; set; }
    }
}
